### ISSUE TITLE
/stats user doesnt work no more

### ISSUE THREAD

**Issue by hndrk-themer** [mkdryden/telegram-stats-bot#21]
Hey, am running the latest docker image. Unfortunately the /stats user command is broken rn.

This is what the Error log looks like:

2023-04-17 17:11:45,690 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/telegram_stats_bot/main.py", line 169, in print_stats
    context.bot.send_message(chat_id=update.effective_chat.id,
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 534, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py", line 203, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 344, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end of italic entity at byte offset 9

**Comment by mkdryden** [comment]
Hmm, that's a weird error. That usually means there is something wrong with the markdown being sent in the message. Would you happen to have an underscore or asterisk in your username? (The thing that starts with @ in your profile) I can probably escape the username better [here](https://github.com/mkdryden/telegram-stats-bot/blob/750427a841f88396f0634e5198dce4e58d895a8f/telegram_stats_bot/stats.py#L775) or just take out the markdown. It doesn't really need it there anyways.

**Comment by hndrk-themer** [comment]
Yes, my username contains an underscore

**Comment by eiger8** [comment]
I can confirm this behaviour
